import { MIGRATION_001_SCHEMA_HISTORY } from "./001-schema-history.js";
import { MIGRATION_002_PROJECTS_AND_MISSIONS } from "./002-projects-and-missions.js";
import { MIGRATION_003_REPOSITORY_REGISTRATIONS } from "./003-repository-registrations.js";
import { MIGRATION_004_GIT_SNAPSHOTS } from "./004-git-snapshots.js";
import { MIGRATION_005_EVIDENCE_SOURCES_AND_TIMELINE } from "./005-evidence-sources-and-timeline.js";
import { MIGRATION_006_CLAIMS_AND_SUPERSESSIONS } from "./006-claims-and-supersessions.js";
import { MIGRATION_007_RUNTIME_OBSERVATIONS } from "./007-runtime-observations.js";
import { MIGRATION_008_TWIN_REVISIONS } from "./008-twin-revisions.js";
import { MIGRATION_009_CODE_MAP_REVISIONS } from "./009-code-map-revisions.js";
import { MIGRATION_010_RECONCILIATION_IMPACT_REVISIONS } from "./010-reconciliation-impact-revisions.js";
import { MIGRATION_011_READINESS_ASSESSMENTS } from "./011-readiness-assessments.js";
import { MIGRATION_012_RELEASE_PASSPORTS } from "./012-release-passports.js";
import { MIGRATION_013_DEMO_WORKSPACES } from "./013-demo-workspaces.js";
import { MIGRATION_014_DEMO_GOLDEN_WORKFLOW } from "./014-demo-golden-workflow.js";

export const FOUNDATION_MIGRATIONS = Object.freeze([
  MIGRATION_001_SCHEMA_HISTORY,
  MIGRATION_002_PROJECTS_AND_MISSIONS,
  MIGRATION_003_REPOSITORY_REGISTRATIONS,
  MIGRATION_004_GIT_SNAPSHOTS,
  MIGRATION_005_EVIDENCE_SOURCES_AND_TIMELINE,
  MIGRATION_006_CLAIMS_AND_SUPERSESSIONS,
  MIGRATION_007_RUNTIME_OBSERVATIONS,
  MIGRATION_008_TWIN_REVISIONS,
  MIGRATION_009_CODE_MAP_REVISIONS,
  MIGRATION_010_RECONCILIATION_IMPACT_REVISIONS,
  MIGRATION_011_READINESS_ASSESSMENTS,
  MIGRATION_012_RELEASE_PASSPORTS,
  MIGRATION_013_DEMO_WORKSPACES,
  MIGRATION_014_DEMO_GOLDEN_WORKFLOW
]);
